version: "3"

services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: postgres_db
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "core.settings.celery", "worker", "-l", "info"]
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - redis

#  flower:
#    container_name: flower
#    build: .
#    command: ["python", "-m", "flower", "-A", "core.settings.celery", "--broker=redis://redis:6379/0"]
#    ports:
#      - "5555:5555"
#    network_mode: "host"
#    depends_on:
#      - redis


volumes:
  postgres_data:
