GENRE_CHOICES = (
    ("fiction", "Fiction"),
    ("non_fiction", "Non-fiction"),
    ("mystery", "Mystery"),
    ("fantasy", "Fantasy"),
    ("science_fiction", "Science Fiction"),
    ("biography", "Biography"),
    ("self_help", "Self-help"),
    ("romance", "Romance"),
    ("thriller", "Thriller"),
    ("historical", "Historical"),
    ("adventure", "Adventure"),
    ("horror", "Horror"),
    ("poetry", "Poetry"),
    ("drama", "Drama"),
    ("comedy", "Comedy"),
    ("children", "Children"),
    ("young_adult", "Young Adult"),
)
